package garvanza.fm.nio;

public enum Commands {
	MAKE_RECORD,
	RETURN_RECORDS,
	DEACTIVATE_RECORD,
	RESET_PRODUCT_INVENTORY,
	PRODUCT_INVENTORY_ADD,
	REQUEST_SHOPMAN,
	SEARCH_PRODUCTS,
	SEARCH_PROVIDERS
}
